name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 23f2000226@ds.study.iitm.ac.in
        run: echo "Hello, world!"
      - name: 23f2001449@ds.study.iitm.ac.in
        run: echo "Hello, world!"
